GCC := g++
CXX_FLAGS := -std=c++17 -g -O3 -Wall -Wextra
SHARED_LIB_FLAGS := -shared -fpic -Wl,-undefined,dynamic_lookup

SRC_PATH := $(ROOT_PATH)/src
SERVER_PATH := $(SRC_PATH)/server
CLIENT_PATH := $(SRC_PATH)/client

LIB_ROOT_PATH := $(SRC_PATH)/lib
SOCKET_LIB_PATH := $(LIB_ROOT_PATH)/socket
ASYNC_ENGINE_LIB_PATH := $(LIB_ROOT_PATH)/AsyncEngine
HELPERS_LIB_PATH := $(LIB_ROOT_PATH)/Helpers
THREADS_LIB_PATH := $(LIB_ROOT_PATH)/Threads

SOCKET_LIB_NAME := async_socket_io
ASYNC_ENGINE_LIB_NAME := async_engine_io
HELPERS_LIB_NAME := async_helpers_io
THREADS_LIB_NAME := async_threads_io

LIBS := -L$(SOCKET_LIB_PATH)/ -l$(SOCKET_LIB_NAME) \
-L$(ASYNC_ENGINE_LIB_PATH)/ -l$(ASYNC_ENGINE_LIB_NAME) \
-L$(HELPERS_LIB_PATH)/ -l$(HELPERS_LIB_NAME)


INCLUDES := -I$(SOCKET_LIB_PATH) \
-I$(ASYNC_ENGINE_LIB_PATH) \
-I$(HELPERS_LIB_PATH) \
-I$(THREADS_LIB_PATH)